language: java
sudo: false # faster builds

script:
  - mvn clean test
  - mvn clean package

before_deploy:
  - export JARBALL=$(ls target/gravitee-repository-elassandra-*.jar)
  - export ZIPBALL=$(ls target/gravitee-repository-elassandra-*.zip)

deploy:
  - provider: releases
    overwrite: true
    draft: false
    api_key:
      secure: "Vb6l58K+W93eJITOFSqYwefWOQ9L8nm7J1y5PDr9Gqsv0y4AxfmrcL6gOz1MvXV+6oUXdRc6tFPWhqxeANtTRJulC+9Q9L7D8/YMOfj5SQ5QTL11lMLFZGdy1iXkgnqpFckXa+NIS0Qfz8FUShy4XEC3meMl8SPTZCwz9Vav1Cfuo6Humf6QiZauCp7bffhy5Uyv41anSlrp45misXD7YmkK2QrN/cnmT9gRmMA5peDTpmsYHJxH1QapDEI1Igb2IsBSzC8PaVcKRIapgIOlYWy9ap/UenjKBouunCxVk4SiZgRCQPJdvKCl/Zo7FsVdnht22g+jsWnXq0geZiieELb14j4/UXZVN6oo53UGNNpgysuxTbL+o5/z4PE/0aseDye2xNd8ZftJ/CAqJI9vLbSPuJ+sc4XnNoD7BC+NF7nN2Vj/JaQGErFqnyC27Ktif8nur0sqrVZihsiOf9jP9usPW+ZMiShHQQtivoLlrPQ2wq2I8cmN3C8fWTTdqZCvKMfiUeJHUjJmFNg21gz8ymdGqLZVEQI1nOdDoiVMK7uVRL9DgfKh35MojxaZI7R3vRSKzPg9QoI13YSeqmrhq3aIiOPO5pG2Xvo8f961UB8d9f7j18CsBCJlc+KG6aNkvlWgVhThI/dl9IST0iCR2kwyoE4eQErcsH6E7Q60zwU="
    file:
      - "$JARBALL"
      - "$ZIPBALL"
    skip_cleanup: true
    on:
      tags: true
      repo: strapdata/gravitee-repository-elassandra