ARG TAG
ARG IMAGE

FROM $IMAGE:$TAG
MAINTAINER Strapdata Team <http://www.strapdata.com>

COPY target/gravitee-repository-elassandra-*.zip $GRAVITEEIO_HOME/plugins/

RUN rm $GRAVITEEIO_HOME/lib/ext/lucene*7.5.0.jar

COPY target/lucene*7.7.2.jar $GRAVITEEIO_HOME/lib/ext/